#include "../main.cpp"
#include "../Refrences.cpp"
#include "../Texture.cpp"
#include "../world/Chunk.cpp"
#include "../world/World.cpp"
#include "../world/blockData.h"
//#include "world/voxels/Block.cpp"
//#include "world/voxels/BlockDataKeyword.h"
//#include "world/voxels/BlockID.h"
#include "../engine/Engine.cpp"
#include "../engine/ShaderProgram.cpp"
#include "../engine/graphics/Camera.cpp"
#include "../engine/graphics/Shader.cpp"
#include "../engine/graphics/Window.cpp"

#include "../../3rdparty/glad.c"
#include "../../3rdparty/stb_image.cpp"